// web/src/pages/auth/Register/index.jsx
import React, { Component } from 'react'
import { Form, Input, Button, Space, Radio, message as Message } from 'antd'
import { register } from '@/api'
import './index.scss'

export default class Register extends Component {

  // 注册
  register = async(values) => {
    try {
      await register(values)
      Message.success('注册成功！')
      setTimeout(() => {
        this.props.history.push('/login')
      }, 1000)
    } catch (error) {
      console.log('注册失败！',error)
    }
  }

  gotoLogin = () => this.props.history.push('/login')
  onFinishFailed = (errorInfo) => console.log('提交表单失败！', errorInfo)

  render() {
    
    return (
      <div data-component="register">
        <div className="register flex-row">
          <div className="reg-form">
            <div className="reg-title">欢迎注册！</div>
            <Form
              // {...this.layout}
              layout="vertical"
              name="basic"
              onFinish={this.register}
              onFinishFailed={this.onFinishFailed}
            >
              <Form.Item
                label="用户名"
                name="username"
                rules={[{ required: true, message: '请输入用户名!' }]}
              >
                <Input placeholder="请输入用户名~" />
              </Form.Item>

              <Form.Item
                label="密码"
                name="password"
                rules={[{ required: true, message: '请输入密码!' }]}
              >
                <Input.Password placeholder="请输入密码~" />
              </Form.Item>

              <Form.Item
                label="昵称"
                name="nickname"
                rules={[{ required: true, message: '请输入昵称!' }]}
              >
                <Input placeholder="请输入昵称~" />
              </Form.Item>
              
              <Form.Item
                label="姓名"
                name="name"
                rules={[{ required: true, message: '请输入姓名!' }]}
              >
                <Input placeholder="请输入姓名~" />
              </Form.Item>

              <Form.Item
                name="gender"
                label="性别"
                rules={[{ required: true, message: '请选择性别' }]}
              >
                <Radio.Group>
                  <Radio value={0}>男</Radio>
                  <Radio value={1}>女</Radio>
                </Radio.Group>
              </Form.Item>

              <Form.Item
                label="手机号"
                name="phone"
                rules={[{ required: true, message: '请输入手机号!' }]}
              >
                <Input placeholder="请输入手机号~" />
              </Form.Item>

              <Form.Item className="button-area">
                <Space>
                  <Button type="primary" htmlType="submit">注册</Button>
                  <Button type="primary" onClick={this.gotoLogin}>返回登录</Button>
                </Space>
              </Form.Item>
            </Form>
          </div>
        </div>
      </div>
    )
  }
}

// admin/src/views/auth/Register.vue
<template>
  <div class="login-wrap flex-row">
    <div class="bg"></div>
    <div class="form box-shadow">
      <div class="title text-black">注册</div>
      <el-form ref="form" :model="form" :rules="rules" label-position="top" size="medium" aria-autocomplete="off">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" placeholder="请输入用户名"></el-input>
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="form.password" type="password" placeholder="请输入密码"></el-input>
        </el-form-item>
        <el-form-item label="昵称">
          <el-input v-model="form.nickname" placeholder="请输入昵称"></el-input>
        </el-form-item>
        <el-form-item label="手机号">
          <el-input v-model="form.phone" placeholder="请输入手机号"></el-input>
        </el-form-item>
      </el-form>
      <el-button class="button" type="primary" @click="register">注册</el-button>
      <div style="text-align: center;margin-top: 10px">
        已有账号？<span style="cursor: pointer" class="text-skyblue" @click="backLogin">返回登录</span>
      </div>
    </div>
  </div>
</template>

<script>
import { usersUrl } from '@/api'
export default {
  data() {
    return {
      form: {},
      rules: {
        username: [
          { required: true, message: '请输入用户名', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入密码', trigger: 'blur' }
        ]
      }
    }
  },
  methods: {
    register() {
      this.$refs.form.validate(async valid => {
        if (valid) {
          const res = this.$http.post(usersUrl,this.form)
          if(res.state === 200) {
            this.$message.success('注册成功')
          }
        }
      })
      
    },
    backLogin() {
      this.$router.push('/login')
    }
  }
}
</script>

<style lang="scss" scoped>
.login-wrap{
  width: 100vw;
  height: 100vh;
  justify-content: center;
  align-items: center;
  &::after{
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: url('~@/assets/bg.jpg') no-repeat center center;
    background-size: 100% 100%;
    opacity: 0.2;
    z-index: -1;
    filter: grayscale(70%);
  }
}

.form{
  padding: 10px 10px 20px;
  width: 500px;
  border-radius: 10px;
  backdrop-filter: saturate(180%) blur(20px);
  background: rgba($color: #ffffff, $alpha: .5);
}
.title{
  text-align: center;
  font-size: 28px;
}
.button{
  width: 100%;
}
</style>
