// admin/src/views/auth/Login.vue
<template>
  <div class="login-wrap flex-row">
    <div class="form">
      <div class="title text-white">空澄的个人空间管理端</div>
      <el-form ref="form" :model="form" :rules="rules" label-position="top" size="medium">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" prefix-icon="el-icon-user" placeholder="请输入用户名"></el-input>
        </el-form-item>
        <el-form-item label="密码" prop="password">
          <el-input v-model="form.password" prefix-icon="el-icon-lock" type="password" placeholder="请输入密码"></el-input>
        </el-form-item>
      </el-form>
      <el-button size="medium" class="button" type="primary" @click="login" >登录</el-button>
      <div style="text-align: center; margin-top: 10px">
        没有账号？<span style="cursor: pointer" class="text-skyblue" @click="gotoRegister">立即注册</span>
      </div>
    </div>
  </div>
</template>

<script>
import { loginUrl } from '@/api'
import { setToken } from '@/utils/auth'
export default {
  data() {
    return {
      form: {},
      rules: {
        username: [
          { required: true, message: '请输入用户名', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入密码', trigger: 'blur' }
        ]
      }
    }
  },
  methods: {
    gotoRegister() {
      this.$router.push('/register')
    },
    async login() {
      this.$refs.form.validate(async valid => {
        if (valid) {
          const { token } = await this.$http.post(loginUrl, this.form)
          if (token) {
            setToken(token)
            this.$router.push('/')
          } 
        }
      })
    }
  }
}
</script>

<style lang="scss" scoped>
.login-wrap{
  width: 100vw;
  height: 100vh;
  background: url('~@/assets/bg.jpg') no-repeat center center;
  background-size: 100% 100%;
  justify-content: center;
  align-items: center;
}
.form{
  padding: 10px 10px 20px;
  width: 500px;
  border-radius: 10px;
  backdrop-filter: saturate(180%) blur(20px);
  background: rgba($color: #ffffff, $alpha: .5);
}
.title{
  text-align: center;
  font-size: 28px;
  padding: 10px 0;
}
.button{
  width: 100%;
}
</style>

// web/src/pages/auth/Login/index.jsx
import React, { Component } from 'react'
import { Form, Input, Button, Space } from 'antd'
import { login } from '@/api'
import { setToken, setUsername } from '@/utils/auth'
import './index.scss'

export default class Login extends Component {

  // 登录
  login = async(values) => {
    // console.log('成功', values)
    try {
      const { token } = await login(values)
      setToken(token)
      setUsername(values.username)
      this.props.history.push('/')
    } catch (error) {
      console.log('登录失败！',error)
    }
  }
  // 跳转前往注册页面
  gotoRegister = () => this.props.history.push('/register')
  // 表单提交失败
  onFinishFailed = (errorInfo) => console.log('提交表单失败！', errorInfo)
  render() {
    
    return (
      <div data-component="login">
        <div className="login flex-row">
          <div className="lg-form">
            <div className="lg-title">React管理端框架</div>
            <Form
              // {...this.layout}
              layout="vertical"
              name="basic"
              initialValues={{ remember: true }}
              onFinish={this.login}
              onFinishFailed={this.onFinishFailed}
            >
              <Form.Item
                label="用户名"
                name="username"
                rules={[{ required: true, message: '请输入用户名!' }]}
              >
                <Input placeholder="请输入用户名~" />
              </Form.Item>

              <Form.Item
                label="密码"
                name="password"
                rules={[{ required: true, message: '请输入密码!' }]}
              >
                <Input.Password placeholder="请输入密码~" />
              </Form.Item>

              <Form.Item className="button-area">
                <Space>
                  <Button type="primary" htmlType="submit">登录</Button>
                  <Button type="primary" onClick={this.gotoRegister} >立即注册</Button>
                </Space>
              </Form.Item>
            </Form>
          </div>
        </div>
      </div>
    )
  }
}
